In [1]:
import torch




In [2]:
# create an empty floating point tensor
x = torch.empty(1, 3)
print(x)

# Creation of default floating point tensor (float32) filled with ones
y = torch.ones(2,5)

# Creation of Integer tensor from existing data; Bad way
zbad = torch.IntTensor([[1, 2,3], [4,5,6]])
print(zbad)

z = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float)
print(z)

tensor([[1.3452e-43, 0.0000e+00, 6.7262e-44]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
# Inspecting a Tensor

print(x.size())
print(x.shape) #usually used in preference to size()

print(z.type()) # the underlying class; this will be dependent on the backing device (so there are different FloatTensor implementations for different devices)
print(z.device) # the actual backing device (which isn't just cpu/gpu, but could tell you which gpu...)

torch.Size([1, 3])
torch.Size([1, 3])
torch.FloatTensor
cpu


In [10]:
# Setting values

x[0,0] = 0
print(x)

x[0,1:2] = 0 # same as numpy
print(x)


x.fill_(1.125)
print(x)




tensor([[ 0.0000e+00,  4.5689e-41, -2.1736e-21]])
tensor([[ 0.0000e+00,  0.0000e+00, -2.1736e-21]])
tensor([[1.1250, 1.1250, 1.1250]])


In [11]:
# 1st order statistics

print(x.mean())
print(x.std())

tensor(1.1250)
tensor(0.)


In [13]:
print(x.sum().shape)
x.sum()
x.sum().item()

torch.Size([])


3.375

In [15]:
z.numpy()
print(z.cpu().numpy())
print(z[0,0].item())

[[1. 2. 3.]
 [4. 5. 6.]]
1.0


In [16]:
# Element-wise operations

x = torch.tensor([10., 20., 30.])
y = torch.tensor([11., 21., 31.])

print(x + y)
print(x - y)
print(x * y)
print( x / y)
print(x**2)
print(torch.sin(x))
print(x==10)
print(x <= 20)
print((x <=20) & (x==10))


tensor([21., 41., 61.])
tensor([-1., -1., -1.])
tensor([110., 420., 930.])
tensor([0.9091, 0.9524, 0.9677])
tensor([100., 400., 900.])
tensor([-0.5440,  0.9129, -0.9880])
tensor([ True, False, False])
tensor([ True,  True, False])
tensor([ True, False, False])


In [17]:
# Matrix multiplication

x = torch.tensor([ 10., 20., 30.]) # 1d tensor
m = torch.tensor([[ 0., 0., 1. ],[ 0., 2., 0. ],[ 3., 0., 0. ]]) #m is a 2d tensor

try:
    print(torch.mm(m,x))
except Exception as e: # torch.mm does not support broadcasting
    print("Error: " + str(e))
print(torch.matmul(m,x)) # matmul matrix multiplication with broadcasting
print(m @ x) # shorthand for matmul


Error: Dimension out of range (expected to be in range of [-1, 0], but got 1)
tensor([30., 40., 30.])
tensor([30., 40., 30.])


In [18]:
# Unsqueezing tensors- unsqueezing adds another dimension: 

x = torch.tensor([10., 20., 30.])
print(x.shape)
x.unsqueeze_(-1) # in-place unsqueeze, adding the new dimension in the last position (so we create a _column_ vector)
print(x.shape)
print(x.t().shape)
print(torch.mm(m,x))

torch.Size([3])
torch.Size([3, 1])
torch.Size([1, 3])
tensor([[30.],
        [40.],
        [30.]])


In [20]:
# Reshape tensors

x2 = x.reshape(3) # reshape back to 1d 3 element array
print(x2)

tensor([10., 20., 30.])
